name: cron

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - run: npm ci
      - run: npm --workspace=collector run start $(pwd)/archive/$(date +'%Y-%m-%d')
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add archive
          git commit -m "[skip ci] chore: update $(date +'%Y-%m-%d')"
          git push origin main
      - uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: "packages/collector/*.png"
