name: cron

on:
  push:
    paths-ignore:
      - "archive/**"
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: "npm"
      - run: npm ci
      - run: npm --workspace=collector run start $(pwd)/archive/raw/$(date +'%Y-%m-%d')
      - run: git status
        if: always()
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add archive
          git commit -m "chore: update $(date +'%Y-%m-%d')"
          git push origin main
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: "packages/collector/*.png"
